create table if not exists issues (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  month text not null,
  title text not null,
  theme text not null,
  intro text not null,
  cover_image_url text,
  published_at date default now()
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  issue_id bigint not null references issues(id) on delete cascade,
  title text not null,
  event_date text,
  event_type text,
  summary text not null,
  stats jsonb not null default '[]'::jsonb,
  video_url text,
  order_index int not null default 0
);

create table if not exists event_images (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  image_url text not null,
  caption text,
  order_index int not null default 0
);

alter table issues enable row level security;
alter table events enable row level security;
alter table event_images enable row level security;

drop policy if exists "public read issues" on issues;
drop policy if exists "public read events" on events;
drop policy if exists "public read event_images" on event_images;

create policy "public read issues"
on issues for select
using (true);

create policy "public read events"
on events for select
using (true);

create policy "public read event_images"
on event_images for select
using (true);
